<a href="https://colab.research.google.com/github/sdd261/Machine_Learning/blob/main/Encoding_Categorical_Data_%7C_Ordinal_Encoding_%7C_Label_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


In [2]:
df=pd.read_csv('customer.csv')

In [3]:
df.sample(5)

age  gender   review education purchased
8    65  Female  Average        UG        No
16   59    Male     Poor        UG       Yes
35   74    Male     Poor    School       Yes
21   32    Male  Average        PG        No
33   89  Female     Good        PG       Yes

In [9]:
df = df.iloc[:,2:]

In [10]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [16]:
x_train

review education
3      Good        PG
19     Poor        PG
26     Poor        PG
5   Average    School
33     Good        PG
25     Good    School
40     Good    School
2      Good        PG
32  Average        UG
14     Poor        PG
13  Average    School
27     Poor        PG
21  Average        PG
30  Average        UG
4   Average        UG
23     Good    School
24  Average        PG
36     Good        UG
37  Average        PG
17     Poor        UG
11     Good        UG
10     Good        UG
12     Poor    School
6      Good    School
0   Average    School
15     Poor        UG
35     Poor    School
22     Poor        PG
45     Poor        PG
16     Poor        UG
38     Good    School
9      Good        UG
41     Good        PG
46     Poor        PG
34  Average    School
44  Average        UG
48     Good        UG
49     Good        UG
20  Average    School
29  Average        UG

In [17]:
#define the categories in order like poor=0, average=1, good=2
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])


In [21]:
oe.fit(x_train)



OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
x_train=oe.transform(x_train)

In [24]:
x_train

array([[2., 2.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [1., 2.],
       [1., 1.],
       [1., 1.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [1., 2.],
       [0., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [1., 0.],
       [1., 1.]])

In [29]:
oe.categories_


[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [31]:
from sklearn.preprocessing import LabelEncoder


In [32]:
le = LabelEncoder()


In [33]:
le.fit(y_train)


LabelEncoder()

In [34]:
le.classes_


array(['No', 'Yes'], dtype=object)

In [35]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [39]:
y_train


array([0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1])

In [40]:
y_test

array([1, 1, 0, 1, 1, 0, 0, 0, 0, 0])